### ISSUE TITLE
.NET Interactive Notebooks is now Polyglot Notebooks

### ISSUE THREAD

**Issue by jianwu13** [markjprice/cs11dotnet7#1]
[.NET Interactive Notebooks is now Polyglot Notebooks!](https://devblogs.microsoft.com/dotnet/dotnet-interactive-notebooks-is-now-polyglot-notebooks/)

**Comment by markjprice** [comment]
This is already in the errata:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-4-8---pros-and-cons-of-the-net-interactive-notebooks-extension-downloading-and-installing-visual-studio-code
