### ISSUE TITLE
Chapter 16 - Pages 707 & 708

### ISSUE THREAD

**Issue by BobMolloy** [markjprice/cs11dotnet7#12]
Bullet 6: The layout statement is not in _Host.cshtml
Bullet 7: The file _Layout.cshtml does not exist.

**Comment by markjprice** [comment]
Thank you, Bob. I have added an errata item for this here: https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-707---reviewing-the-blazor-server-project-template
