### ISSUE TITLE
Breaking interpolated strings / C# and .NET 7 Modern Cross-Platform Development Essentials.

### ISSUE THREAD

**Issue by macros1980** [markjprice/cs11dotnet7#16]
Please check that your issue is not already in the [errata aka list of corrections and improvements](https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/README.md). Please note that PRs will be ignored because code in the repo must match the print book already published. Please raise an issue instead so I can handle it appropriately. All issues will be entered into the errata once closed. They will also be fixed in the next book edition.

You can delete the note above after reading it. Please complete as much information below as possible so that I can understand and fix the issue quickly. Screenshots can be especially useful. You can drag and drop images into the box. Thank you! 

Chapter: 
Page Number: 83
Section Title: Formatting using interpolated strings
Step Number: 1
Problem to fix:
**// The following statement must be all on one line.**
Console.WriteLine($"{numberOfApples} apples cost {pricePerApple *
numberOfApples:C}");
Suggested solution:
As of .NET 7 interpolated strings can be broken to more lines in interpolation placeholders like in this examples. It compiles just fine. Of course with older .NET breaking lines in interpolated strings are not supported.

Other useful information e.g. OS, coding tools, and so on:
Compiled with .NET 7 / checked with .NET 6

**Comment by markjprice** [comment]
Thank you! I have added an errata item for this:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-83---formatting-using-interpolated-strings
