### ISSUE TITLE
Page 272 - Step 4

### ISSUE THREAD

**Issue by alikzalikz** [markjprice/cs11dotnet7#18]
Chapter: 06
Page Number: 272 
Section Title: Defining struct types
Step Number: 04
Problem to fix: output show format

![problem](https://user-images.githubusercontent.com/74256693/212544361-f118b69b-0a9e-4b6c-b8a0-39360fb0319d.png)

**Comment by markjprice** [comment]
Sorry, but I don't understand what you mean by "output show format". The output is as shown in the book:
![image](https://user-images.githubusercontent.com/14040265/212886595-001efdd0-03e0-4913-bc24-d9ef088c02f9.png)
If your output is different, please show both a screenshot of your output and your code.

**Comment by alikzalikz** [comment]
hello Mr. price
no i mean, on every page of book output shows like step 6
but output in step 4 shows like code
just a small issue
and, thank you for this great book :)🙏

![example](https://user-images.githubusercontent.com/74256693/212891925-4913cc8c-edf8-497e-b853-6e396525937c.png)

**Comment by markjprice** [comment]
Ah, I see what you mean. Yes, I've added this as an errata item and it'll be formatted correctly in the 8th edition. Thank you!
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-272---defining-struct-types
