### ISSUE TITLE
Sample code not compiling (page 345)

### ISSUE THREAD

**Issue by bavaro89** [markjprice/cs11dotnet7#20]
Chapter: 10 (Working with Data Using Entity Framework Core)
Page Number: 345 (epub)
Section Title: Modifying data with EF Core / Inserting entities
Step Number: 4

Problem to fix: Method *ListProducts* is expecting an int array, but gets a single int, so it won't compile (*cannot convert from 'int' to 'int[]?'*):
**ListProducts(productIdToHighlight: resultAdd.productId);**)

Suggested solution: Cf page 346 where it is working:
**ListProducts(productIdsToHighlight: new[] { resultAdd.productId });**

**Comment by markjprice** [comment]
Thanks for taking the time to raise this. It is already in the errata: https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-477---inserting-entities

**Comment by bavaro89** [comment]
OK, looked for it but could not find it, sorry!
