### ISSUE TITLE
Could not find the Project Packt.Share

### ISSUE THREAD

**Issue by nirzaf** [markjprice/cs11dotnet7#22]
Chapter: 11

Most of the sample code referring to Packt.Share, but could not find that project. Any idea? @markjprice 

![image](https://user-images.githubusercontent.com/18024930/215846080-bc261bb7-5ae8-4125-b78c-fab259410b78.png)

**Comment by markjprice** [comment]
`Packt.Shared` is not a project, it is a namespace. 

All of the entity models in the four projects listed below should have their classes defined in the `Packt.Shared` namespace, for example: 
https://github.com/markjprice/cs11dotnet7/blob/main/vs4win/PracticalApps/Northwind.Common.EntityModels.SqlServer/Product.cs

Entity model projects:
- [Northwind.Common.DataContext.SqlServer](https://github.com/markjprice/cs11dotnet7/tree/main/vs4win/PracticalApps/Northwind.Common.DataContext.SqlServer)
- [Northwind.Common.DataContext.Sqlite](https://github.com/markjprice/cs11dotnet7/tree/main/vs4win/PracticalApps/Northwind.Common.DataContext.Sqlite)
- [Northwind.Common.EntityModels.SqlServer](https://github.com/markjprice/cs11dotnet7/tree/main/vs4win/PracticalApps/Northwind.Common.EntityModels.SqlServer)
- [Northwind.Common.EntityModels.Sqlite](https://github.com/markjprice/cs11dotnet7/tree/main/vs4win/PracticalApps/Northwind.Common.EntityModels.Sqlite)
