### ISSUE TITLE
Managing the Filesystem typo

### ISSUE THREAD

**Issue by DarioBosco** [markjprice/cs11dotnet7#26]
Chapter: 09
Page Number:  N/D (WebReader)
Section Title: Managing the filesystem (Managing directories)
Step Number: 1
Problem to fix: The following code is shown three times

`WriteLine($"Does it exist? {Path.Exists(newFolder)}");`

Exixts() is a method from System.IO.Directory and not from System.IO.Path
Suggested solution: Change it to `WriteLine($"Does it exist? {Directory.Exists(newFolder)}");` which also is redundant as we statically imported System.IO.Directory

Other useful information e.g. OS, coding tools, and so on: VS2022 + Resharper
![image](https://user-images.githubusercontent.com/81041446/216957857-99da63a1-2396-465a-9b8b-02f998b4ebbb.png)
![image](https://user-images.githubusercontent.com/81041446/216957822-c4138c7d-a0d2-44e0-8982-196bd764f698.png)

**Comment by DarioBosco** [comment]
My bad, had .NET6 as default for some reason after a Windows fresh install

**Comment by markjprice** [comment]
Thanks! I've added an errata item for this:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-399---managing-directories

**Comment by DarioBosco** [comment]
It was actually correct. I had my project set as .NET6 instead of .NET7 after a windows fresh install.

I had closed the issue. Sorry about that. Your code works perfectly on .NET7

Sent from Proton Mail for iOS

Il lun, feb 6, 2023 alle 12:28, Mark J. Price ***@***.***> ha scritto:
