### ISSUE TITLE
Subsections order in the section "Setting a breakpoint and starting debugging" of chapter four

### ISSUE THREAD

**Issue by MAS-OUD** [markjprice/cs11dotnet7#28]
In the section **Setting a breakpoint and starting debugging** of chapter four, _Writing, Debugging, and Testing Functions_, at the end of the subsection **Using Visual Studio 2022** there's the following paragraph:

> If you do not want to see how to use Visual Studio Code to start debugging, then you can skip the next
section and continue to the section titled _Navigating with the debugging toolbar_.

In the book, the section **Using Visual Studio Code** appears after the section **Navigating with the debugging toolbar**. I think there might be a mistake here.

**Comment by markjprice** [comment]
Thank you. I have added an item for this issue:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-166---setting-a-breakpoint-and-starting-debugging---using-visual-studio-2022
