### ISSUE TITLE
Page 180 Binding TraceSwitch

### ISSUE THREAD

**Issue by bettesn** [markjprice/cs11dotnet7#29]
I cannot get past a runtime error on the line "configuration.GetSection("PacktSwitch").Bind(ts);" (see attached).  The value field is populated (with "Info") in the object "configuration" but is null in the bind.

I have recreated the entire solution and copied the sample code from the book - same problem.

![bind error](https://user-images.githubusercontent.com/43040802/219357291-69e8aa54-60c2-4d73-b93b-793aed5eb06b.png)

**Comment by markjprice** [comment]
Please show the contents of your file named `appsettings.json`. It should be:
```json
{
  "PacktSwitch": {
    "Level": "Info"
  }
}
```

**Comment by bettesn** [comment]
Hi there,

 

Thanks for responding.

 

This is what I have in that file.  I ended up copying all the solution files from the book download to eliminate typos.

 



 

Nick

 

Nick Bettes

Director

 

Nick Bettes Consulting

M: +44 7540 769 937

T: +44 333 014 4042

Beech Hill House, Wood Lane, Beech Hill, Berkshire RG7 2BE

**Comment by markjprice** [comment]
Sorry, but I cannot help unless I have more information. The exception you got says it cannot parse the string value for the enum. That could be because you are looking at one file but it is reading a different one. Or the value is wrong. Please show as much information as possible, for example, the code will output the full path and filename of the appsettings.json file that it is reading from. Please show all output and the contents of that file.

**Comment by bettesn** [comment]
It’s ok I don’t expect you to provide tech support for the price of a book!  It must be something in my setup that is affecting it.  I’m getting on with the rest of the book with no other problems.

 

I’ll deal with this config issue if and when I need it for real.

 

Nick

 

Nick Bettes

Director

 

Nick Bettes Consulting

M: +44 7540 769 937

T: +44 333 014 4042

Beech Hill House, Wood Lane, Beech Hill, Berkshire RG7 2BE

**Comment by Matrix-Zhang** [comment]
same issue, the json key is 'PacktSwitch:Level'?
![图片](https://user-images.githubusercontent.com/1751829/222935001-4f659b67-10a6-4bda-a3dc-8b5ddeeddfa3.png)

**Comment by huynhloc-1110** [comment]
It seems like the new version (7.0.3) of `Microsoft.Extensions.Configuration.Binder` has some changes that break the old code in the book. I also had the same issue as you and tried changing the version of the `Binder` in `Instrumenting.csproj` from 7.0.3 back to 7.0.0 to match the version in the book and it worked fine after that.
I also tried changing back to 7.0.3 again and the exception showed again.

Here is my package reference when the error happened:
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="7.0.3" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="7.0.0" />
  </ItemGroup>

And after fixing:
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="7.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="7.0.0" />
  </ItemGroup>

**Comment by bettesn** [comment]
Thanks for resolving this and updating me.

 

Nick Bettes

Director

 

Nick Bettes Consulting

M: +44 7540 769 937

T: +44 333 014 4042

Beech Hill House, Wood Lane, Beech Hill, Berkshire RG7 2BE
