### ISSUE TITLE
.NET Interactive Notebook Extension Name Change

### ISSUE THREAD

**Issue by LibanFarah124** [markjprice/cs11dotnet7#3]
The extension name that we have been told to download has been changed from ".NET Interactive Notebook" to
---> "Polyglot Notebooks"

I was confused at first when I couldn't find it, but after looking I managed to find out this information online.

**Comment by markjprice** [comment]
Thank you for taking the time but this is already in the errata:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-4-8---pros-and-cons-of-the-net-interactive-notebooks-extension-downloading-and-installing-visual-studio-code
