### ISSUE TITLE
Section: "Requiring properties to be set during instantiation", Adding the PacktLibraryModern project

### ISSUE THREAD

**Issue by MAS-OUD** [markjprice/cs11dotnet7#33]
In the section **Requiring properties to be set during instantiation** of chapter five (page: 231), it would be helpful to remind the reader that after the project **PacktLibraryModern** was created, it must be added as a _Project Reference_ to the **PeopleApp** project. In case the reader forgets this, the class **Book** will be unknown in the **Program.cs** file.

**Comment by markjprice** [comment]
Thanks! I have added an item for this:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-231---requiring-properties-to-be-set-during-instantiation
