### ISSUE TITLE
Operator ?? on page 237

### ISSUE THREAD

**Issue by MAS-OUD** [markjprice/cs11dotnet7#35]
On page 237, chapter five, the reader encounters the operator for the first time in the book and is probably unfamiliar with it. This operator is explained later in chapter six, but I think you could explain it here or let the reader know that it will be demystified later in the book.

**Comment by markjprice** [comment]
Thanks! I have added an item for this:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/improvements.md#page-237---implementing-functionality-using-methods
