### ISSUE TITLE
Problem in JSON example

### ISSUE THREAD

**Issue by mjza** [markjprice/cs11dotnet7#36]
Chapter: 2
Page Number: 
Section Title: Raw interpolated string literals
Step Number: 
Problem to fix: used comma instead of colon  "calculation", "{{{ 1 + 2 }}}"
Suggested solution: "calculation": "{{{ 1 + 2 }}}"

**Comment by markjprice** [comment]
Thanks! I've added an item for this:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/improvements.md#page-69---raw-interpolated-string-literals
