### ISSUE TITLE
Pattern matching with objects: Defining flight passengers

### ISSUE THREAD

**Issue by MAS-OUD** [markjprice/cs11dotnet7#38]
On pages 242 through 244, to be able to run the _flight passengers_ example I have to add the line `using static Packt.Shared.FlightPatterns;` or prefix class names with `FlightPatterns.`.

**Comment by markjprice** [comment]
I have created an improvement item for this:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/improvements.md#page-241---defining-flight-passengers
