### ISSUE TITLE
immutable objects concept

### ISSUE THREAD

**Issue by MAS-OUD** [markjprice/cs11dotnet7#39]
On page 244, the concept of **immutable** objects is used. I think it would be a good idea to give a definition for this concept at the beginning of this section. The reader might not be aware of this already.

**Comment by markjprice** [comment]
Immutability is introduced on page 161. In the next edition, I will add a bit more text to this definition to make it clearer what it means.

![image](https://user-images.githubusercontent.com/14040265/223765035-cd5f9891-7f78-4ee8-9433-fee617e3e299.png)
