### ISSUE TITLE
A minor issue in page 263

### ISSUE THREAD

**Issue by MAS-OUD** [markjprice/cs11dotnet7#43]
At the bottom of page 263, there is a comment in the code that reads
`/// ...if they are equal...`
in harmony with other comments, I think it should be
`// ...if they are equal...`

**Comment by markjprice** [comment]
Thanks! I have added an item for this:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-263---comparing-objects-using-a-separate-class
