### ISSUE TITLE
Going To Implementation of a method

### ISSUE THREAD

**Issue by MAS-OUD** [markjprice/cs11dotnet7#48]
On page 339, step 3, when I right-click in the `Count` method and select **Go To Implementation** the file `Enumerable [from metadata]` opens not the file `Count.cs [SourceLink]`.

**Comment by MAS-OUD** [comment]
The [solution](https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-37---getting-definitions-of-types-and-their-members) doesn't work for me. No matter whether the checkbox **Enable navigation to Source Link and Embedded sources** is checked or unchecked, selecting **Go To Implementation** opens the file `... [from metadata]` for me.

**Comment by markjprice** [comment]
There must be something wrong with your Visual Studio installation because when **Enable navigation to Source Link and Embedded sources** is checked it is supposed to enable navigation to Source Link. You might want to raise an issue with Microsoft.
