### ISSUE TITLE
An improvement: Using interpolated strings on page 351

### ISSUE THREAD

**Issue by MAS-OUD** [markjprice/cs11dotnet7#49]
on page 351, the expressions `"x" + i.ToString();` and `"y" + i.ToString();` can be replaced by `$"x{i}"` and `$"y{i}"`, respectively.

**Comment by markjprice** [comment]
Thanks. I've added an item for this:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/improvements.md#page-351---using-non-net-standard-libraries
