### ISSUE TITLE
Chapter 10 - Working With Data Using Entity Framework Core

### ISSUE THREAD

**Issue by chadwickgeyser** [markjprice/cs11dotnet7#5]
Please check that your issue is not already in the [errata aka list of corrections and improvements](https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/README.md). Please note that PRs will be ignored because code in the repo must match the print book already published. Please raise an issue instead so I can handle it appropriately. All issues will be entered into the errata once closed and fixed in the next book edition.

Chapter: 10
Page Number: 926 of Kindle edition
Section Title: Modifying data with EF Core
Problem to fix: Parameter name, type does not match argument name, type
Suggested solution: Change argument name, type
Other useful information e.g. OS, coding tools, and so on:

Hello! I believe I've spotted a slight error. In Program.Modifications.cs the method signature looks as such:

static void ListProducts(int[]? productIdsToHighlight = null)

However, when it's called from Program.cs (page 929 of Kindle edition) an int value is passed instead of int[]:

ListProducts(productIdToHightlight: resultAdd.productId);

Two problems as far as I can tell: The argument name passed is singular - productIdToHighlight vs productIdsToHighlight in the method signature. Also the value passed is int rather than int[] in the method signature.

To preserve the functionality of being able to pass in int[] values I changed the calling code to:

ListProducts(productIdsToHightlight: new int[] { resultAdd.productId });

Hopefully I'm correct about this!

**Comment by markjprice** [comment]
Hi, 

Yes, you are correct. Thank you!

I have added this to the errata: https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-477---inserting-entities
