### ISSUE TITLE
Outputting the generated numbers in "Generating random numbers for games and similar apps"

### ISSUE THREAD

**Issue by MAS-OUD** [markjprice/cs11dotnet7#51]
on page 358, the code doesn't output anything. I suggest the code writes the generated random numbers to the console:
```
...
WriteLine($"dieRoll = {dieRoll}");

...
WriteLine($"randomReal = {randomReal}");

...
for (int i = 0; i < arrayOfBytes.Length; i++)
{
    WriteLine($"arrayOfBytes[{i}] = {arrayOfBytes[i]}");
}
```

**Comment by markjprice** [comment]
The code shown is supposed to be read, not entered, because it is so obvious. You only need to enter code when instructed to do so by numbered steps. Of course, readers are welcome to write any code they like and output anything they like.
