### ISSUE TITLE
IsNan instead of IsNaN

### ISSUE THREAD

**Issue by GoPapaSmurf** [markjprice/cs11dotnet7#53]
Hello,

On p.75, section "_Chapter 2 - Speaking C# → Working with variables → Storing real numbers → Comparing double and decimal types_", in the last paragraph, there is a spelling mistake, it is written `IsNan` instead of `IsNaN`:
> They also have methods for checking for these special values like `IsInfinity` and `IsNan.`

**Comment by markjprice** [comment]
Thanks! I have added an errata item for this issue:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-75---comparing-double-and-decimal-types
