### ISSUE TITLE
Scaffolding models using an existing database

### ISSUE THREAD

**Issue by MAS-OUD** [markjprice/cs11dotnet7#54]
On page 453, running the command in step 2 with the `dotnet-ef` version 7.0.4 creates class files that aren't exactly similar to those shown in the book. For example, the Category class doesn't have a constructor, or the two `DbSet<T>` properties of the Northwind class are not set to null.

**Comment by markjprice** [comment]
Thanks! I have added an item for this issue:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-454---scaffolding-models-using-an-existing-database
