### ISSUE TITLE
Chapter 4: TraceSwitch binding

### ISSUE THREAD

**Issue by danielwithme** [markjprice/cs11dotnet7#55]
Since Microsoft.Extensions.Configuration.Binder 7.0.3 or later, this setting will throw exception:
`{
    "PacktSwitch": {
      "Level": "Info"
    }
}`

To fix it, change the above configuration into:
`{
    "PacktSwitch": {
      "Level": "Info",
      "Value":  "3"
    }
}`

Reference: https://github.com/dotnet/runtime/issues/82998

**Comment by markjprice** [comment]
Yes, this is already in the errata:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-178---reviewing-project-packages
