### ISSUE TITLE
Missed interpolated string symbol in the section 'Updating entities'

### ISSUE THREAD

**Issue by MAS-OUD** [markjprice/cs11dotnet7#57]
At step 2 on page 478, the `$` character is missing in the line `WriteLine("Increase price success for ID: {resultUpdate.productId}.");`.

**Comment by markjprice** [comment]
Thanks! I have added this item:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-478---updating-entities
