### ISSUE TITLE
Chapter 14 - Building Websites Using the MVC Pattern 

### ISSUE THREAD

**Issue by chadwickgeyser** [markjprice/cs11dotnet7#6]
Please check that your issue is not already in the [errata aka list of corrections and improvements](https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/README.md). Please note that PRs will be ignored because code in the repo must match the print book already published. Please raise an issue instead so I can handle it appropriately. All issues will be entered into the errata once closed. They will also be fixed in the next book edition.

You can delete the note above after reading it. Please complete as much information below as possible so that I can understand and fix the issue quickly. Screenshots can be especially useful. You can drag and drop images into the box. Thank you! 

Chapter: 14
Page Number: 1208 - kindle edition
Section Title: Defining a typed view
Step Number: 3
Problem to fix: Typo in data-* attribute
Suggested solution: Fix typo
Other useful information e.g. OS, coding tools, and so on:

Hello! There is a slight typo in the book code for the carousel indicators:
PracticalApps > Northwind.Mvc > Views > Home > Index.cshtml

`<li data-bs-target="#categories" data-slide-to="@c" class="@currentItem"></li>`

Should be:
`<li data-bs-target="#categories" data-bs-slide-to="@c" class="@currentItem"></li>`

The code in the github repo is correct.

**Comment by markjprice** [comment]
Thanks! I have added an errata item:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-627---defining-a-typed-view
