### ISSUE TITLE
Example of CallerArgumentExpression - Page 182

### ISSUE THREAD

**Issue by FQanbari** [markjprice/cs11dotnet7#60]
Chapter: 4
Page Number: 182
Section Title: Logging information about your source code
Step Number: Example of this section
Problem to fix: The name 'condition' does not exist in the current context
Suggested solution:
using System.Diagnostics; // Trace
using System.Runtime.CompilerServices; // [Caller...] attributes
partial class Program
{
    static void LogSourceDetails(
    bool condition,
    [CallerMemberName] string member = "",
    [CallerFilePath] string filepath = "",
    [CallerLineNumber] int line = 0,
    [CallerArgumentExpression("condition")] string expression = "")
    {
        Trace.WriteLine(string.Format(
        "[{0}]\n {1} on line {2}. Expression: {3}",
        filepath, member, line, expression));
    }
}

**Comment by markjprice** [comment]
You probably entered the wrong code. It should be:
```cs
[CallerArgumentExpression(nameof(condition))] string expression = "")
```
as shown in the following screenshot from the book:
![image](https://user-images.githubusercontent.com/14040265/232246289-afd38d50-aa40-4fe7-b62c-7c6afc025a54.png)

**Comment by FQanbari** [comment]
thank you for your response, I updated my visual studio and disappeared this error.
