### ISSUE TITLE
Requiring properties to be set during instantiation

### ISSUE THREAD

**Issue by DrAvriLev** [markjprice/cs11dotnet7#61]
Please check that your issue is not already in the [errata aka list of corrections and improvements](https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/README.md). Please note that PRs will be ignored because code in the repo must match the print book already published. Please raise an issue instead so I can handle it appropriately. All issues will be entered into the errata once closed. They will also be fixed in the next book edition.

You can delete the note above after reading it. Please complete as much information below as possible so that I can understand and fix the issue quickly. Screenshots can be especially useful. You can drag and drop images into the box. Thank you! 

Chapter: 5
Page Number: 231
Section Title: Requiring properties to be set during instantiation
Step Number: 
Problem to fix: 
Suggested solution:
Other useful information e.g. OS, coding tools, and so on:
I get an error saying : 
Error	CS0246	The type or namespace name 'Book' could not be found (are you missing a using directive or an assembly reference?)	PoepleApp	D:\# C# 11 and .NET 7\C# Leraning files\Chapter05\PersonApp\Program.cs	162	Active

I know I need to reference the new class. How I do it here, please?

**Comment by markjprice** [comment]
Have you read this errata item that might help you:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-231---requiring-properties-to-be-set-during-instantiation

**Comment by DrAvriLev** [comment]
Thank you very much. I knew I was missing a step. 
I figured that issue by adding manually the include statement to the PeopleApp properties...
I'm going to edit my pdf file so save this change. 
Thanks for your prompt answer.
👍

**Comment by DrAvriLev** [comment]
Yes I did. 

Thanks

 

Dr. Lev
