### ISSUE TITLE
Solution title in figure 11.1

### ISSUE THREAD

**Issue by MAS-OUD** [markjprice/cs11dotnet7#62]
In Figure 11.1 on page 495, the solution title is `Chapter12` instead of `Chapter11`.

![Untitled](https://user-images.githubusercontent.com/65589587/233394660-12406210-eccb-4f4c-8591-6ec2d38d20e5.png)

**Comment by markjprice** [comment]
Thank you. I have added an item for this:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-495---filtering-entities-with-where
