### ISSUE TITLE
Visual Studio Code Integrated Terminal Configuration

### ISSUE THREAD

**Issue by cmkaya** [markjprice/cs11dotnet7#64]
Hello,

I don't know whether it is an issue or not, but I have found some missing on the topic, as I explained below.

Chapter: 4

Page Number: 163

Section Title: Using the Visual Studio Code integrated terminal during debugging

Problem to fix: 
In the first sentence of the ordered list, it is stated as "Open the launch.json file". However, it is not clear where the file is. I found the solution on [stackoverflow](https://stackoverflow.com/questions/67495792/where-is-the-launch-json-file-in-visual-studio-code)

Suggested solution:
I think it could be beneficial for beginners to explain where to find this file. 

Other useful information e.g. OS, coding tools, and so on:

**Comment by markjprice** [comment]
The Step 1 instructions do say where the file is, "in the `.vscode` folder", as shown in the following screenshot of the book:

![image](https://user-images.githubusercontent.com/14040265/235321654-bc92111b-f144-4d3c-a7fd-49bff681ea4a.png)

**Comment by markjprice** [comment]
I have also created an improvement item for this:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/improvements.md#page-163---using-the-visual-studio-code-integrated-terminal-during-debugging

**Comment by cmkaya** [comment]
I saw that after opening an issue. You have already explained it on page 167. Thank you! 

Actually, I have another question that is different. Should I ask it here, or open another Issue?
