### ISSUE TITLE
Creating a class library

### ISSUE THREAD

**Issue by cmkaya** [markjprice/cs11dotnet7#65]
Hi there!

Chapter: 4
Page Number: 185 
<img width="804" alt="Statement" src="https://user-images.githubusercontent.com/75931847/235571474-cb90937d-380d-4e54-94db-8693acfb62c7.png">

Problem to fix: As it is seen on the image, to create a new class library, we are told to use `dotnet new console` command. However, it creates a new console app, not a class library.

Suggested solution: We have to type `dotnet new classlib` in the terminal.

**Comment by markjprice** [comment]
This is already an errata:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-185---creating-a-class-library-that-needs-testing

**Comment by cmkaya** [comment]
I missed it.
