### ISSUE TITLE
Chapter 14 - Building Websites Using the MVC Pattern

### ISSUE THREAD

**Issue by chadwickgeyser** [markjprice/cs11dotnet7#7]
Chapter: 14
Page Number: 1250 - kindle edition
Section Title: Varying cached data by query string
Step Number: 1
Problem to fix: VaryByQuery renamed
Suggested solution: change to SetVaryByQuery
Other useful information e.g. OS, coding tools, and so on:

Hello! 
In PracticalApps > Northwind.Mvc > Program.cs the book code shows:

`options.AddPolicy("views", p => p.VaryByQuery(""));`

Looks like VaryByQuery was renamed to SetVaryByQuery:

`options.AddPolicy("views", p => p.SetVaryByQuery(""));`

[https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/7.0/output-caching-renames](https://learn.microsoft.com/en-us/dotnet/core/compatibility/aspnet-core/7.0/output-caching-renames)

**Comment by markjprice** [comment]
Thanks! I have added an errata item for this:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-649---varying-cached-data-by-query-string
