### ISSUE TITLE
.Net standard is legacy but is still used?

### ISSUE THREAD

**Issue by edgarrenza** [markjprice/cs11dotnet7#72]
Chapter: 1 - Hello, C#! Welcome, .NET!
Section Title: Understanding .NET Standard

I don't understand why if .NET Standard is used by .Net platform (SDK, runtime, etc) you said that it is now legacy:

".NET Standard is now officially legacy. There will be no new versions of .NET Standard so its GitHub repository is archived, as you can read about in the following tweet: https://twitter.com/dotnet/status/1569725004690128898. "

I'm feeling frustrated by the different names, versions, what is used and what is not.

Could you please explain or give me mor information about it?. Thanks

**Comment by markjprice** [comment]
Imagine you are applying for a job in IT support for a bank. Windows 11 is the latest version and Windows 8 is legacy. But the bank might still have employees using Windows 8 as well as Windows 11. If you want the job, you need to know how to support Windows 8 as well as Windows 11. 

It's similar with developer platforms like .NET. .NET Standard is legacy, but if you want a job with an organization that still has projects that use it, then you need to learn it. If you are only going to use .NET for your own development projects, then you can ignore it and only use .NET 7.

If you only need to use one of the latest .NET versions, for example, .NET 6 or .NET 7, then you do not need .NET Standard. If you need to support older platforms like .NET Framework or Xamarin, then .NET Standard allows you to create class libraries that work with all of the various .NET platforms.

You are only on Chapter 1. You will see practical examples of when you might use .NET Standard in later chapters like 5 and 6. Just keep going through the chapters and don't worry about it for now.

**Comment by markjprice** [comment]
You can learn more about .NET Standard from the book links:
https://github.com/markjprice/cs11dotnet7/blob/main/book-links.md#net-standard

**Comment by edgarrenza** [comment]
many thanks Mr. Mark, I am surprised by your quick response. It was clear. I will follow your recommendations and continue learning with your book.
