### ISSUE TITLE
No OmniSharp: Select Project

### ISSUE THREAD

**Issue by gitLehman** [markjprice/cs11dotnet7#75]
Please check that your issue is not already in the [errata aka list of corrections and improvements](https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/README.md). Please note that PRs will be ignored because code in the repo must match the print book already published. Please raise an issue instead so I can handle it appropriately. All issues will be entered into the errata once closed. They will also be fixed in the next book edition.

You can delete the note above after reading it. Please complete as much information below as possible so that I can understand and fix the issue quickly. Screenshots can be especially useful. You can drag and drop images into the box. Thank you! 

Chapter: 1
Page Number: 31 
Section Title:  Adding a second project using Visual Studio code
Step Number: 7
Problem to fix: Omnisharp does not show. I decided to skip the step.
Suggested solution: Is their an alternative?
Other useful information e.g. OS, coding tools, and so on:

In Chapter 1 page 29, right underneath the text highlighted in black, it says "...the equivalent components for your operating system will be downloaded and installed". And it did. I remember some dependencies were installed. I could not remember if it was Omnisharp though. So I proceed to the next instruction until I encounter step 7 on page 31 explicitly saying type Omni (I think on command palette) but it is not showing up.

I am using MacBook Air 2017 version 12.6.5.

**Comment by markjprice** [comment]
You must have installed the pre-release version of the C# extension. This version 2.0 and later, does not use Omnisharp. To match the book instructions, click **Switch to Release Version**, as shown in the screenshot below:

![image](https://github.com/markjprice/cs11dotnet7/assets/14040265/249301b2-d061-4398-b285-2d1205f132a4)

Meanwhile, I will investigate and add an errata item to explain to readers how to do the equivalent in version 2.0.

**Comment by markjprice** [comment]
I have added errata items for this issue:

https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-8---installing-other-extensions

https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-28---writing-code-using-visual-studio-code

https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-31---adding-a-second-project-using-visual-studio-code

**Comment by markjprice** [comment]
I have written an improvement item if you want to use the newer version:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/improvements.md#page-31---adding-a-second-project-using-visual-studio-code

**Comment by gitLehman** [comment]
I appreciate the update. I am enjoying the book and I am glad I found it
through Derek Banas videos.


Best Regards,
Lehman Maynite

**Comment by gitLehman** [comment]
Hi Mark,

The PDF copy of the book is pretty hard to navigate. I have encountered PDF
books where there would be links that could jump from one chapter to
another. I hope this can be an improvement in the future releases.
