### ISSUE TITLE
Page 149

### ISSUE THREAD

**Issue by DrAvriLev** [markjprice/cs11dotnet7#84]
When creating the new class "Program.Functions.cs", VS generate also a namespace. That, I think, creates an error # CS0103 saying that 
"The name 'TimesTable' does not exist in the current context.

Only after removing the namespace line, the error disapear and all come back to normal.

What happend?

Avri

**Comment by markjprice** [comment]
Yes, Step 4 shows the entire file. You must not define a namespace. This is covered here: https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/improvements.md#page-149---writing-a-times-table-function

**Comment by DrAvriLev** [comment]
Thank you :)
