### ISSUE TITLE
Exercise Solutions - Where are they?

### ISSUE THREAD

**Issue by Folkvar** [markjprice/cs11dotnet7#85]
Hi,

I'm trying to find the exercise solutions. I've found some in the B18856_Appendix.pdf file but not exericse 2.3. Where is the solution for that?

Regards
Mike

**Comment by markjprice** [comment]
Hi Mike,

![image](https://github.com/markjprice/cs11dotnet7/assets/14040265/83711a37-b49f-4ce9-9979-1672b1a6b7c5)

Code solutions for all exercises are in the GitHub repo, for example: https://github.com/markjprice/cs11dotnet7/tree/main/vs4win/Chapter02/Ch02Ex03Numbers
