### ISSUE TITLE
Relational pattern + property pattern example missing decimal literal value suffix "M"

### ISSUE THREAD

**Issue by NoelArzola** [markjprice/cs11dotnet7#87]
Example code missing decimal literal value suffix "M"
Chapter: 5
Page Number: 244
Section Title: Enhancements to pattern matching in C# 9 or later
Problem to fix: `FirstClassPassenger { AirMiles: > 35000 } => 1500,`
Suggested solution: `FirstClassPassenger { AirMiles: > 35000 } => 1500M,`
Other useful information e.g. OS, coding tools, and so on:
<img width="1441" alt="Screenshot 2023-10-22 at 13 08 15" src="https://github.com/markjprice/cs11dotnet7/assets/23287951/b10a804e-4f72-4b73-8fc0-5fb8d2840981">

**Comment by markjprice** [comment]
Thanks. I have added this to the errata:
https://github.com/markjprice/cs11dotnet7/blob/main/docs/errata/errata.md#page-244---enhancements-to-pattern-matching-in-c-9-or-later
